### PR TITLE
Add support for different test isolation levels

### PR DESCRIPTION
**Pull request by chschroe74**
Normally, each test method has its own Weld instance, thus ensuring total
isolation; however, this also means that multiple instances exist for
application-scoped beans (one per test method), which can be a problem for
some applications.

This commit allows to set the isolation level of a test class to
"PER_CLASS", which causes a single Weld instance to be used for the whole
class.

### CODE REVIEW

**Comment by seanf** [comment]
@chschroe74 Thanks for the pull request!

Looking at the [build results in Travis](https://travis-ci.org/BrynCooke/cdi-unit/builds/395786803), there's something wrong with the new PER_CLASS isolation level when running on Weld 2.3 or later. 

The failure can be reproduced in IntelliJ by running all tests in cdi-unit-tests. Nearly all the tests after TestNoIsolation break, as if Weld was left in a bad state.

**Comment by seanf** [comment]
This is the failure message: https://travis-ci.org/BrynCooke/cdi-unit/jobs/395786817#L6669

**Comment by chschroe74** [comment]
I fixed the problem, and now the build is green. Strange thing is that the errors did not show up when I ran the test suite in IntelliJ. (I did that yesterday before committing, and tried again today.)

**Comment by seanf** [comment]
Thanks for fixing that @chschroe74. The general approach seems fine, so please go ahead and add those Javadocs you mentioned.

But can you remind me what's going on with TestConfiguration? It seems that the `testMethod` may be null now (which makes sense because the Weld deployment is no longer related to individual test methods), but I'm having trouble tracing the implications through the code.  Seems like it might mess with the ProducerConfigExtension. Ah yes, the test `TestProducerConfig` breaks if I add `@Isolation(IsolationLevel.PER_CLASS)`. I'm a bit rusty on ProducerConfig, but yes, that makes perfect sense, because the individual test methods choose which configuration to give the producer.

So could you please document the limitation that ProducerConfig doesn't work with IsolationLevel.PER_CLASS (yet)? I know, it would help if I had documented ProducerConfig when I implemented that feature, but a brief note would do.  We're going to need some sort of documentation section for PER_METHOD vs PER_CLASS anyway. (See the file docs/index.md)

Also, could I get you to add a check (for attempting to use ProducerConfig with PER_CLASS)? Probably in methodBlock.

I do think ProducerConfig could work with PER_CLASS (we just need to find a way to pass the testMethod reference to the producer methods), but for now I'm fine with documenting it as a limitation of PER_CLASS. Unless you _want_ to tackle it.

**Comment by chschroe74** [comment]
Sorry for not responding earlier, but I was quite busy over the week.

I have done a more or less complete rewrite of the ProducerConfigExtension and finally managed to add support for the ProducerConfig annotation in combination with the PER_CLASS mode.

However, I encountered one problem: I found that per default the test classes are implicitly annotated with `@ApplicationScoped` by the TestScopeExtension. This means that only one single instance is created, so the producer methods are called only once. This was no problem before because each test method had its own Weld instance, but it now causes the test to still not work as expected.

I fixed this by implicitly annotating a PER_CLASS test class with `@Dependent` instead of `@ApplicationScoped`. This might generally be more appropriate, but I assume there are reasons for using application scope, so I did not want to change it.

Please decide if that approach is acceptable.

I have also added some JavaDocs. Should I also add a section to the documentation, or will you (or someone else) take care of that?

**Comment by chschroe74** [comment]
Hmm. The tests fail for Weld 1.1 because the class javax.enterprise.inject.spi.ProducerFactory cannot be found. This is strange ... The class should be available since CDI 1.1, and I indeed found it in the cdi-api-1.1 jar file. Do you have an explanation why it is missing?

Apart from that, I found a problem with the test class having the dependent scope (see my previous comment). It seems that now fields in the test class which are annotated with `@Produces @Mock` do no longer work. The problem is that the instance that is injected into other classes is no longer the same as the instance in the test class, so any mocked methods will not be available in the other class. I am not sure if this can easily be fixed because it is the correct behavior from the CDI perspective. (When a dependent bean contains a producer method or field, a new instance of the bean is expected to be created for each produced class.)

I think about making the test class application-scoped again, or even better, check if the ProducerConfig annotation is actually used in the class and only switch to dependent scope if it is. It might also be useful to allow explicit scope annotations to the test class. Both should not be too difficult to implement.

What do you think?

**Comment by seanf** [comment]
On Sun, 1 Jul 2018 at 00:55, Christian <notifications@github.com> wrote:

> Sorry for not responding earlier, but I was quite busy over the week.
>
> I have done a more or less complete rewrite of the ProducerConfigExtension
> and finally managed to add support for the ProducerConfig annotation in
> combination with the PER_CLASS mode.
>
Excellent, thank you!

> However, I encountered one problem: I found that per default the test
> classes are implicitly annotated with @ApplicationScoped by the
> TestScopeExtension. This means that only one single instance is created, so
> the producer methods are called only once. This was no problem before
> because each test method had its own Weld instance, but it now causes the
> test to still not work as expected.
>
> I fixed this by implicitly annotating a PER_CLASS test class with
> @Dependent instead of @ApplicationScoped. This might generally be more
> appropriate, but I assume there are reasons for using application scope, so
> I did not want to change it.
>
> Please decide if that approach is acceptable.
>

Hmm. I'll have to think about it. Depending on setup, some tests use
RequestScoped. I'm beginning to wonder if we need a custom
TestMethodScoped, but that's probably overkill.

Dependent is probably fine. I can't think right now whether the lack of
interceptors would matter.

The other (related) issue is using ApplicationScoped in one mode, versus
Dependent in PER_CLASS mode. This should be completely backwards compatible
for existing PER_METHOD users, but could it be confusing for users who
switch between modes?

> I have also added some JavaDocs. Should I also add a section to the
> documentation, or will you (or someone else) take care of that?
>
A new section in the documentation would be very helpful, thank you. Even a
draft would help.

**Comment by seanf** [comment]
On Sun, 1 Jul 2018 at 02:12, Christian <notifications@github.com> wrote:

> Hmm. The tests fail for Weld 1.1 because the class
> javax.enterprise.inject.spi.ProducerFactory cannot be found. This is
> strange ... The class should be available since CDI 1.1, and I indeed found
> it in the cdi-api-1.1 jar file. Do you have an explanation why it is
> missing?
>

It's confusing, but Weld 1.1 implements CDI 1.0. eg see
https://mvnrepository.com/artifact/org.jboss.weld/weld-core/1.1.10.Final

> Apart from that, I found a problem with the test class having the
> dependent scope (see my previous comment). It seems that now fields in the
> test class which are annotated with @Produces @Mock do no longer work.
>
You probably already did, but please make sure you add a test case for
that. Thanks!

> The problem is that the instance that is injected into other classes is no
> longer the same as the instance in the test class, so any mocked methods
> will not be available in the other class.
>
Can you explain more about the problem here? "any mocked methods will not
be available in the other class" - why is that? Are there multiple mock
objects, but the one which was configured with behaviour ("mocked"),
perhaps in a @Before method, is not the one which was used in the test? Or
is this about mock behaviours configured in one test method not coming
across to the next test method?

> I am not sure if this can easily be fixed because it is the correct
> behavior from the CDI perspective. (When a dependent bean contains a
> producer method or field, a new instance of the bean is expected to be
> created for each produced class.)
>
Technically, in CDI, I think the @Dependent (or unscoped) producer method
is supposed to be invoked each time it is injected (eg once per test
method). If that producer method keeps returning the same instance, I think
that's legal. Then again, these are producer fields, not methods. So I
guess it normally depends on the scope of the object holding those fields.

It's confusing because the producers are part of the same class which needs
to inject them. I'm not sure off hand if that's normally legal in CDI.

But I don't think these Mock producer fields are working in the normal CDI
way, so perhaps we can do things differently. For instance, does the test
instance have to be a CDI bean at all? What if we just inject its fields
once per test method, a bit like DeltaSpike's BeanProvider.injectFields
does?


> I think about making the test class application-scoped again,
>
Okay...

> or even better, check if the ProducerConfig annotation is actually used in
> the class and only switch to dependent scope if it is.
>
That sounds kind of complex and potentially surprising.

Perhaps we need a third mode here. PER_METHOD, PER_CLASS_NO_SHARING and
PER_CLASS_SHARED_INSTANCE (better naming welcome).


> It might also be useful to allow explicit scope annotations to the test
> class. Both should not be too difficult to implement.
>
Explicit scope annotations could be quite useful, but then a lack of
annotations might imply (from a CDI perspective) Dependent scope, whereas
ApplicationScoped is the current behaviour. But perhaps we don't have to
follow that CDI convention here.

And I think we would still have the problem that certain scopes work as
expected, and others fail in random ways.


> What do you think?
>
We need to keep in mind that there are two related use cases here. (1) Per
class Weld deployments for the sake of test performance, and (2) per method
deployments which deliberately retain some state between methods (seems
like a bad idea, but apparently there's a use case for it). Personally I
wouldn't use the latter mode if there was an option for "per class"
deployments with a minimum of shared state between tests.

I think I need a diagram/table showing how all these options interrelate.

   - (Existing) PER_METHOD (ApplicationScoped test instance per test
   method): slow but full isolation, each producer is called exactly once, no
   problem for Mocks or ProducerConfig.
   - PER_CLASS_SHARED_INSTANCE (ApplicationScoped test instance per class,
   shared by test methods [1]): each producer is called once per test method.
   Mocks are the same between test methods, but ProducerConfig breaks. (I
   would be okay with this as a documented limitation with a startup check.)
   - PER_CLASS_NO_SHARING (Dependent test instance per test method[2]):
   each producer is called once per test method. ProducerConfig is okay, but
   Mock instances have some sort of a problem(??)

Types of shared state:

   - Weld deployment
   - The test class instance(s)
   - Mock object instances


Did I get that right?

[1] JUnit 4 normally ensures that each test method uses a different
instance of the test class for better isolation. (TestNG has a different
philosophy here.). If we share the test instance via Weld for less
isolation, that goes against JUnit norms, but no problem. However I think a
shared instance is fundamentally incompatible with ProducerConfig (since it
offers per-method configuration of producers).
[2] Do Dependent test instances break things like
@InRequestScope/InRequestInterceptor? If so, perhaps a custom scope like
TestMethodScoped could help.

**Comment by ikysil** [comment]
Dear @chschroe74  ,

Could you please rebase your branch on the latest changes in master?
There were changes to the build system to restore the build functionality on TravisCI which are not picked up without a rebase.

**Pull request closed without merging**
