### PR TITLE
feat: JUnit 5 Support

### LINKED ISSUE #103: Question: JUnit 5 Support?
Hey!
Are there any plans to upgrade or support [JUnit 5 extension model](http://junit.org/junit5/docs/current/user-guide/#extensions)?

### PR DESCRIPTION
**Pull request by ikysil**
Resolves #103 
Replaces #144

### CODE REVIEW

**Comment by graben** [comment]
Hi @ikysil 
CdiJUnit5Extension.createTestInstance() seems to need something like
```
if (testConfiguration == null) {
    beforeAll(extensionContext);
}
```

to avoid `NullPointerException` with maven-surefire-plugin

**Comment by ikysil** [comment]
> Hi @ikysil CdiJUnit5Extension.createTestInstance() seems to need something like
> 
> ```
> if (testConfiguration == null) {
>     beforeAll(extensionContext);
> }
> ```
> 
> to avoid `NullPointerException` with maven-surefire-plugin

I don't see this happening in neither of the modules.
Would you mind to provide a reproducer?

**Comment by graben** [comment]
> Hi @graben
> 
> > ... CdiJUnit5Extension.createTestInstance() seems to need something like
> > ```
> > if (testConfiguration == null) {
> >     beforeAll(extensionContext);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to avoid `NullPointerException` with maven-surefire-plugin
> 
> I don't see this happening in neither of the modules. Would you mind to provide a reproducer?

Sure. [test.zip](https://github.com/user-attachments/files/16488568/test.zip)
It seems that the implementing interface for logging is causing surefire to call createTestInstance earlier than expected!?

**Comment by ikysil** [comment]
The presence of the `@TestInstance(PER_CLASS)` annotation changes the order of the callbacks.

**Comment by graben** [comment]
@ikysil: Is an automatic synchronization between `@TestInstance` and `@Isolation` planed? It might cause issues if not.

**Comment by ikysil** [comment]
Let's have a discussion #290 and then implement it separately.

**Pull request merged**
