### PR TITLE
Issue #195 - Migrate to Jakarta EE

### PR DESCRIPTION
**Pull request by martin-g**
This is a draft PR for an attempt to migrate to Jakarta EE.

There are two main issues:
- It seems there is no Jakarta EE version of Apache DeltaSpike (https://issues.apache.org/jira/browse/DELTASPIKE-1430)
- I was not able to find the Jakarta EE version of JBoss RestEasy. 
https://resteasy.github.io/2020/01/15/resteasy-3100final-jakarta/ and 
https://resteasy.github.io/2019/10/30/resteasy-440final-moving-to-jakarta-artifacts-and-much-more/ claim to move to Jakarta APIs but it seems it is just about using jakarta groupId but the package names in 4.6.0 are still javax.**. I've tried to work it around by using temporary custom javax classes that delegate to the jakarta impls but it is not finished.

### CODE REVIEW

**Comment by vanta** [comment]
@martin-g the proper version of `resteasy` is unfortunatelly `6.x`, see my discussion here https://github.com/resteasy/resteasy/discussions/2953

**Comment by martin-g** [comment]
Thanks for the info, @vanta !
Unfortunately there is no much interest/enthusiasm in Java EE developers to migrate their projects to Jakarta ...

**Comment by ikysil** [comment]
> Thanks for the info, @vanta ! Unfortunately there is no much interest/enthusiasm in Java EE developers to migrate their projects to Jakarta ...

What is the landscape for legacy Java EE vs modern Jakarta ? Would you suggest fully embracing Jakarta and sun-setting JavaEE support?

**Comment by martin-g** [comment]
> What is the landscape for legacy Java EE vs modern Jakarta ? Would you suggest fully embracing Jakarta and sun-setting JavaEE support?

Yes!
Users of `javax.**` can still an old/released version.
But everything new should use jakarta.**

**Comment by ikysil** [comment]
Closing this PR in favor of #230

**Pull request closed without merging**
